wizem_api_homepage:
    path:     /test
    defaults: { _controller: wizemApiBundle:Default:index }

wizem_api_event:
    type: rest
    prefix: /api
    resource: wizem\ApiBundle\Controller\EventController
    name_prefix:  api_event_ # naming collision