services:
    wizem_api.event.handler:
        class: wizem\ApiBundle\Handler\EventHandler
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            entityClass: "wizem\EventBundle\Entity\Event"
            form.factory: "@form.factory"
            logger: "@api_logger"
