wizem_event:
    resource: "@wizemEventBundle/Resources/config/routing.yml"
    prefix:   /

wizem_api:
    resource: "@wizemApiBundle/Resources/config/routing.yml"
    prefix:   /

wizem_user:
    resource: "@wizemUserBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"