# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    log_file_max_number : 10

services:
    # Symfony 3 hack for new version after composer update
    fos_user.doctrine_registry:
        alias: doctrine
    api_logger:
            class: Symfony\Bridge\Monolog\Logger
            arguments: [api]
            calls:
                - [pushHandler, [@api_handler]]
    api_handler:
            class: Monolog\Handler\RotatingFileHandler
            arguments: [%kernel.logs_dir%/%kernel.environment%.api.log, %log_file_max_number%]
    user_logger:
            class: Symfony\Bridge\Monolog\Logger
            arguments: [user]
            calls:
                - [pushHandler, [@user_handler]]
    user_handler:
            class: Monolog\Handler\RotatingFileHandler
            arguments: [%kernel.logs_dir%/%kernel.environment%.user.log, %log_file_max_number%]

    user.form.registration:
        class: wizem\UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: wizem_user_registration }
