# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    log_file_max_number : 10

services:
    api_logger:
            class: Symfony\Bridge\Monolog\Logger
            arguments: [api]
            calls:
                - [pushHandler, [@api_handler]]
    api_handler:
            class: Monolog\Handler\RotatingFileHandler
            arguments: [%kernel.logs_dir%/%kernel.environment%.api.log, %log_file_max_number%]
