event:
    path:     /
    defaults: { _controller: "wizemEventBundle:Event:index" }

event_show:
    path:     /{id}/show
    defaults: { _controller: "wizemEventBundle:Event:show" }

event_new:
    path:     /new
    defaults: { _controller: "wizemEventBundle:Event:new" }

event_create:
    path:     /create
    defaults: { _controller: "wizemEventBundle:Event:create" }
    methods:  POST

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "wizemEventBundle:Event:edit" }

event_update:
    path:     /{id}/update
    defaults: { _controller: "wizemEventBundle:Event:update" }
    methods:  [POST, PUT]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "wizemEventBundle:Event:delete" }
    methods:  [POST, DELETE]
