wizem_event_event:
    path:     /
    defaults: { _controller: "wizemEventBundle:Event:index" }

wizem_event_event_show:
    path:     /{id}/show
    defaults: { _controller: "wizemEventBundle:Event:show" }

wizem_event_event_new:
    path:     /new
    defaults: { _controller: "wizemEventBundle:Event:new" }

wizem_event_event_edit:
    path:     /{id}/edit
    defaults: { _controller: "wizemEventBundle:Event:edit" }
    methods:  [POST, PUT]

wizem_event_event_delete:
    path:     /{id}/delete
    defaults: { _controller: "wizemEventBundle:Event:delete" }
    methods:  [POST, DELETE]
