wizem_user_user:
    resource: "@wizemUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

# wizem_user_homepage:
#     path:     /hello/{name}
#     defaults: { _controller: wizemUserBundle:Default:index }