wizem_event_event:
    resource: "@wizemEventBundle/Resources/config/routing/event.yml"
    prefix:   /event

# wizem_event_homepage:
#     path:     /hello/{name}
#     defaults: { _controller: wizemEventBundle:Default:index }
